---
name: "Check symlinks"

on:
  push:
    branches:
      - master

jobs:
  check:
    name: Check for dangling symlinks
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Check symlinks
        shell: bash
        run: |
          sudo apt-get update
          sudo apt install -y libgtk-3-dev --no-install-recommends
          ./configure
          make test
