name: "Check symlinks"

on:
  push
    branches:
    - master

jobs:
  check:
    name: Check for dangling symlinks
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Check symlinks
        shell: bash
        run: |
          sudo apt install -y libgtk-3-dev --no-install-recommends
          ./configure
          make test
